# Generated by Django 6.0.4 on 2026-05-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftStoreApp', '0003_alter_productdb_product_image_cartdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
