# Generated by Django 6.0.4 on 2026-06-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftStoreApp', '0005_cartdb_price_alter_cartdb_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
