# Generated by Django 6.0.4 on 2026-06-15 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftStoreApp', '0008_orderdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ThriftStoreApp.orderdb')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThriftStoreApp.productdb')),
            ],
        ),
    ]
